runtime: nodejs20
service: default

handlers:
  - url: /css
    static_dir: public/css

  - url: /images
    static_dir: public/images

  - url: /contact
    static_files: public/contact.html
    upload: public/contact.html

  - url: /privacy
    static_files: public/privacy.html
    upload: public/privacy.html

  - url: /terms
    static_files: public/terms.html
    upload: public/terms.html

  - url: /.*
    static_files: public/index.html
    upload: public/index.html
